CLC_ArinPatrick/Controllers/MinesweeperController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Minesweeper_ArinPatrick.Models;
using Minesweeper_ArinPatrick.Services.Business;
using Minesweeper_ArinPatrick.Utility;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
namespace Minesweeper_ArinPatrick.Controllers
{
    public class MinesweeperController : Controller
    {
        static Board board;
        Game game = new Game();

        /// <summary>
        /// actual minesweeper game 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [CustomAuthorization]
        public IActionResult Index()
        {
            board = new Board(8);
            board.setUpLiveNeighbors(7);
            board.calculateLiveNeighbors();

            List<Cell> cellList = new List<Cell>();

            foreach (Cell cell in board.grid)
            {
                cellList.Add(cell);
            }
            return View("Index", cellList);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="location"></param>
        /// <returns></returns>
        public IActionResult PartialBoard(string location)
        {
            string[] coordinates = location.Split(',');
            int index = int.Parse(coordinates[0]);
            int row = int.Parse(coordinates[1]);
            int col = int.Parse(coordinates[2]);
            board.grid[row, col].Visited = true;

            board.FloodFill(row, col);

            board.IsGameOverGUI(row, col);

            List<Cell> cellList = new List<Cell>();

            foreach (Cell cell in board.grid)
            {
                cellList.Add(cell);
            }
            return PartialView(cellList);
        }

        /// <summary>
        /// handle button click 
        /// </summary>
        /// <param name="location"></param>
        /// <returns></returns>
        /// 
        public IActionResult HandleCellClick(string location)
        {
            string[] coordinates = location.Split(',');
            int row = int.Parse(coordinates[1]);
            int col = int.Parse(coordinates[2]);
            board.grid[row, col].Visited = true;

            board.FloodFill(row, col);

            board.IsGameOverGUI(row, col);

            List<Cell> cellList = new List<Cell>();

            foreach (Cell cell in board.grid)
            {
                cellList.Add(cell);
            }
   
            return PartialView("PartialBoard", cellList);
        }

        /// <summary>
        /// Right button click  takes the location of button and places a flag on it
        /// This is done by updating partial Board
        /// </summary>
        /// <param name="location"></param>
        /// <returns></returns>
        public IActionResult OnRightButtonClick(string location)
        {
            string[] coordinates = location.Split(',');
            int row = int.Parse(coordinates[1]);
            int col = int.Parse(coordinates[2]);

            board.grid[row,col].Flagged = !board.grid[row,col].Flagged;

            List<Cell> cellList = new List<Cell>();

            foreach (Cell cell in board.grid)
            {
                cellList.Add(cell);
            }
            return PartialView("PartialBoard", cellList);
        }
        /// <summary>
        /// Methods that need to be applied to every single cell
        /// Location determined by row and col
        /// flood fill
        /// isgameover shows if the game can keep going or not
        /// add the cell to the board
        /// </summary>
        /// <param name="location"></param>
        /// <returns></returns>
        public IActionResult OneCell(string location)
        {
            int bttnInt = int.Parse(location);
            string[] coordinates = location.Split(',');
            int row = int.Parse(coordinates[0]);
            int col = int.Parse(coordinates[1]);
            board.grid[row, col].Visited = true;

            board.FloodFill(row, col);

            board.IsGameOverGUI(row, col);

            List<Cell> cellList = new List<Cell>();

            foreach (Cell cell in board.grid)
            {
                cellList.Add(cell);
            }
            return PartialView(cellList.ElementAt(bttnInt));
        }

        /// <summary>
        /// Checks if that game is over. This is displayed under the game board indicating where the game is at
        ///   1 == win
        ///  -1 == lose
        ///   0 == ongoing game
        /// </summary>
        /// <returns></returns>
        public IActionResult CheckGameOver()
        {
            List<Cell> cellList = new List<Cell>();

            UserModel objUser = new UserModel();

            foreach (Cell cell in board.grid)
            {
                cellList.Add(cell);
            }

            if (game.gameOver(cellList) == 1)
            {
                ViewBag.win = "Congrats, you won!";
                MyLogger.GetInstance().info(objUser.Username + "Won the game");
            }
            else if(game.gameOver(cellList) == -1)
            {
                ViewBag.win = "Aw see now you're a loser.";
                MyLogger.GetInstance().info(objUser.Username + "Lost the game");
            }
            else if(game.gameOver(cellList) == 0)
            {
                ViewBag.win = "Nope. Try again.";
            }
            return PartialView("_overPartial");
        }
        public IActionResult OnSave()
        {
            List<Cell> cellList = new List<Cell>();

            foreach (Cell cell in board.grid)
            {
                cellList.Add(cell);
            } 

            StoredGamesDAO storedDAO = new StoredGamesDAO();
            GameObject gameObject = new GameObject(1, JsonConvert.SerializeObject(cellList), HttpContext.Session.GetString("username"));
            bool success = storedDAO.SaveGame(gameObject);

            Tuple<bool, string> resultsTuple = new Tuple<bool, string>(success, JsonConvert.SerializeObject(cellList));

            return View("Results", resultsTuple);
        }
        public IActionResult OnLoad()
        {
            StoredGamesDAO storedDAO = new StoredGamesDAO();
     
            GameObject gameObject = storedDAO.LoadGame(HttpContext.Session.GetString("username"));

            List<Cell> cellList = JsonConvert.DeserializeObject<List<Cell>>(gameObject.JSONString);

            for(int i = 0; i < board.Size; i++)
            {
                for(int j = 0; j < board.Size; j++)
                {
                    board.grid[i,j] = cellList[(i * board.Size) + j];
                }
            }
            return View("Index", cellList);
        }
    }
}

CLC_ArinPatrick/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Minesweeper_ArinPatrick.Models;
using Minesweeper_ArinPatrick.Services.Business;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using NLog;
using Minesweeper_ArinPatrick.Utility;

namespace Minesweeper_ArinPatrick.Controllers
{

    public class UserController : Controller
    {
       
        UserData userDAL = new UserData();

        public IActionResult Index()
        {
            List<Models.UserModel> userList = new List<Models.UserModel>();

            userList = userDAL.GetAllUsers().ToList();

            return View(userList);
        }
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult ProcessLogin(Models.UserModel user)
        {
            //logs when soneone attempts to login
            MyLogger.GetInstance().info("Processing a login attempt");
            MyLogger.GetInstance().info(user.toString());

            CommWDataAccess bs = new CommWDataAccess();
            
            //log if the user is successful, we will log that user
            if(bs.GetUserByUserPass(user))
            {
                MyLogger.GetInstance().info("Login Success");
                HttpContext.Session.SetString("username", user.Username);
                ViewBag.session = HttpContext.Session.GetString("username");
                return View("LoginSuccess", user);
            }
            else
            {
                //if someone fails at a login, we will record what they tried to use
                MyLogger.GetInstance().info("Login Failed");
                HttpContext.Session.Remove("username");
                return View("LoginFailure", user);
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind] Models.UserModel objUser)
        {
            //logs when soneone attempts to login
            MyLogger.GetInstance().info("User is about to create a profile");
            

            if (ModelState.IsValid)
            {
                 userDAL.AddUser(objUser);
                //logs when soneone attempts to login
                MyLogger.GetInstance().info("Processing a Register attempt");
                MyLogger.GetInstance().info("First Name: " + objUser.First);
                MyLogger.GetInstance().info("Last Name: " + objUser.Last);
                MyLogger.GetInstance().info("UserName: " + objUser.Username);
                MyLogger.GetInstance().info("Password: " + objUser.Password);
                MyLogger.GetInstance().info("State: " + objUser.State);
                MyLogger.GetInstance().info("Gender: " + objUser.Gender);
                return RedirectToAction("Index");
            }

            return View(objUser);
        }
    }
}

CLC_ArinPatrick/Views/User/Create.cshtml
@model Minesweeper_ArinPatrick.Models.UserModel
@{
    ViewData["Title"] = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>
<h3>User Registration</h3>
<style>
    body {
        background-color: #46A346;
    }

    .sideImage{
        float:right;
        height: 500px;
        width:700px;
        padding:40px 0px 0px 0px

    }
</style>
<img class="sideImage" src="~/img/tyler.png">
<hr />

@*Html.BeginForm is the Html Helper Extension Method that is used for creating and rendering
    the form in HTML. This method makes your job easier in creating form.
    Syntax: Html.BeginForm("ActionMethod", "ControllerName","Get⁄Post Method")
    ActionMethod – It defines which action method is look for when submit button is clicked.
    ControllerName – It defines, which controller keeps the defined action method.
    Get/Post Method – it defines the method you want to use to send data from form to controller. *@
@using (Html.BeginForm("Create", "User", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class=" = " col-md-4">
            @*(Tag Helpers) -- ValidationSummary.All will display both property and model level
        validations messages while ValidationSummary.ModelOnly will
        display only validation messages that apply to the model level.*@
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="First" class="control-label"></label>
                @*The input Tag Helper binds an HTML <input> element to a mdel expression in the
            razor view.  Is equivalent to model=>model.Name -- the name of the expression is used
            for the asp-for attribute.*@
                <input asp-for="First" class="form-control" />
                @*The validation message tag helper is used to display a validation
            message for a specific property of your model class.  In this
            case "The Name field is required" will be shown if the field
            is submitted blank.*@
                <span asp-validation-for="First" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Last" class="control-label"></label>
                <input asp-for="Last" class="form-control" />
                <span asp-validation-for="Last" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select asp-for="Gender" class="form-control">
                    <option value="">-- Select Gender --</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                    <option value="Other">Other</option>
                </select>

            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Register" class="btn btn-warning" />
            </div>

        </div>
    </div>
}
@*Come down after the current final div*@
<div>
    <a asp-action="Index">Back to List</a>
</div>

@*Used for "client side validation" (javascript).
    It does not let the user send the form if it is not valid
    (according to Model Validation).*@
@section Scripts
{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CLC_ArinPatrick/Views/User/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@*Byte including the @model statement at the top of the view template file,
    you can specify the type of object the view expects.
    This @model(line 5) Directive allows us to access the list of employees
    the controller passed to the view by using the model object
    that's strongly typed *@

@model IEnumerable<Minesweeper_ArinPatrick.Models.UserModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>All Users</h1>
<head>
    <style>
        body {
            background-color: #c1cfe5;
        }
        th,
        td,
        tr,
        thead{
            padding: 10px;
            border: 2px solid black;
        }
    </style>
</head>



    @*The html <p> element represents paragraph*@

    <p>
        @*The <a> tag defines a hyper link that is used to link one page top another*@
        <a asp-action="Create">List of All Users</a>
    </p>


    @*Displaying employee information*@
    @*An html table consists of one <table> element
        and one or more <tr>, <th> and <td> elements.*@
<table class="table table-hover">

 


    @*Table header is used to group header content in the html table*@
    <thead>
        @*<tr> tag is table row, defines a row in an html table*@
        <tr>
            @*The <th> tag defines a header cell in an html table
                the text in the th element are bold and center by default*@
            <th>
                @*The DisplayNameFor shows the name of the property for the string
                    defined in the display attribute of the property*@
                @Html.DisplayNameFor(model => model.First)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Last)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Username)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>

        </tr>

    </thead>

    @*The <tbody> element is used in conjunction with the <thead> and the <tfoot>
        elements to specify each part of a table(Body, header and footer)*@
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                @*<td> Table data defines a standard data cell in html table. The text in the <td> elements
                    are regular and left-aligned by default *@
                <td>
                    @*The DisplayFor() helper method is a strongly typed extension method.
                        It generates an html string for the model object property
                        specified using a lambda expression*@
                    @Html.DisplayFor(modelItem => user.First)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => user.Last)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => user.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => user.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => user.State)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => user.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => user.Username)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => user.Password)
                </td>
                @*
                    <td>
                        <a asp.action="Edit" asp-route-id="@user.UserID">Edit</a>
                        <a asp.action="Details" asp-route-id="@user.UserID">Details</a>
                        <a asp.action="Delete" asp-route-id="@user.UserID">Delete</a>

                    </td>
                *@
            </tr>
        }

    </tbody>

</table>
<div>
    <a asp-action="Login">Login</a>
</div>

CLC_ArinPatrick/Views/User/Login.cshtml
@model Minesweeper_ArinPatrick.Models.UserModel

    <style>
        .logo {
            width: 500px;
           float: right;
        }
        body {
            background-color: #46A346;
        }
    </style>



    <h4>User Login</h4>
    <hr />
    <img class="logo" src="~/img/golf.png">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="ProcessLogin">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Username" class="control-label"></label>
                    <input asp-for="Username" class="form-control" />
                    <span asp-validation-for="Username" class="text-danger"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" type="password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Login" class="btn btn-warning" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

CLC_ArinPatrick/Views/User/LoginFailure.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Minesweeper_ArinPatrick.Models.UserModel

<div>
    <h4>You failed to login.</h4>
    <hr />
    <p>Well, you tried and failed to login using "@Model.Username", and "@Model.Password" so nice try.</p>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {/* id = Model.PrimaryKey */}) |
    <a asp-action="Index">Back to List</a>
</div>

CLC_ArinPatrick/Views/User/LoginSuccess.cshtml
@model Minesweeper_ArinPatrick.Models.UserModel




    <div>
        <style>
            body {
                background-color: lightblue;
            }
        </style>
        <h4>UserModel</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Username)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Username)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Password)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Password)
            </dd>
        </dl>
        <a asp-controller="Minesweeper" asp-action="Index"> Go to Minesweeper </a>
    </div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>